# Generated by Django 5.1.7 on 2025-03-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
    ]
