# Generated by Django 5.1.7 on 2025-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_location_rental_pickup_location_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available_locations',
            field=models.ManyToManyField(related_name='available_cars', to='rental.location'),
        ),
    ]
