# Generated by Django 5.1.7 on 2025-04-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_car_available_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available_locations',
        ),
        migrations.AddField(
            model_name='car',
            name='available_locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.location'),
        ),
    ]
