# Generated by Django 5.1.7 on 2025-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_remove_car_available_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='daily_kilometer_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='extra_kilometer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
