# Generated by Django 5.1.7 on 2025-04-09 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_car_daily_kilometer_limit_car_extra_kilometer_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='maintenance_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Disponibile'), ('rented', 'Noleggiata'), ('maintenance', 'In Manutenzione'), ('reserved', 'Prenotata')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'In Attesa'), ('partial', 'Parziale'), ('completed', 'Completato'), ('refunded', 'Rimborsato')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'In Attesa'), ('confirmed', 'Confermato'), ('in_progress', 'In Corso'), ('completed', 'Completato'), ('cancelled', 'Annullato')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Amministratore'), ('manager', 'Manager'), ('agent', 'Agente'), ('mechanic', 'Meccanico')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cars', to='rental.employee'),
        ),
        migrations.AddField(
            model_name='rental',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rentals', to='rental.employee'),
        ),
    ]
