# Generated by Django 5.1.7 on 2025-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_car_last_maintenance_car_maintenance_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
