# Generated by Django 5.1.7 on 2025-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_alter_rental_payment_status_alter_rental_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='car',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='car',
            name='maintenance_notes',
        ),
        migrations.RemoveField(
            model_name='car',
            name='next_maintenance',
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
